routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function () {
    Route::put('table', 'TableController@changeStatus')->name('change-status');
    Route::post('order/{dish_id}', 'OrderController@createOrder')->name('order-dish');
    Route::get('orderkitchen', 'OrderController@createkitchenOrder')->name('order-dish-kitchen');
    Route::get('/apiorder/{id}', 'TableController@orderdataapi');
    Route::get('checkout/{order_code}/{table_id}', 'OrderController@makePayment')->name('make-payment');
    Route::get('/orderconfirmed/{tableId}', 'OrderController@OrderConfirmed')->name('order-confirmed');
    Route::get('/floordata', 'FloorController@data')->name('floordata');
    Route::get('/userdata', 'UserController@data')->name('userdata');
    Route::get('/categorydata', 'CategoryController@data')->name('categorydata');
    Route::get('/foodcategorydata', 'FoodCategoryController@data')->name('foodcategorydata');
    Route::get('/tabledata', 'TableController@data')->name('tabledata');
    Route::get('/itemdata', 'ItemController@data')->name('itemdata');

});
/******** Custom Routes Start ****************/
/********* Admin Routes Start ***********/
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'HomeController@admin')->name('admin');

    Route::get('/add-data', 'HomeController@addData')->name('addData');

    Route::resource('table', 'TableController');
    Route::get('/table', 'TableController@tableIndex')->name('tableIndex');
    Route::get('table-delete/{id}', 'TableController@destroy')->name('tableDelete');


    Route::resource('user', 'UserController');
    Route::get('/user-delete/{id}', 'UserController@destroy')->name('deleteUser');

    Route::resource('floor', 'FloorController');
    Route::get('floor-delete/{id}', 'FloorController@destroy')->name('floorDelete');

    Route::get('/release/{table_id}', 'TableController@releaseTable')->name('release-table');

    Route::get('/category', 'CategoryController@admin')->name('category');

    Route::resource('category', 'CategoryController');
    Route::get('category-delete/{id}', 'CategoryController@destroy')->name('categoryDelete');

    Route::resource('foodCategory', 'FoodCategoryController');
    Route::get('food-Category-Delete/{id}', 'FoodCategoryController@destroy')->name('foodCategoryDelete');

    Route::get('/item', 'ItemController@admin')->name('item');


    Route::resource('item', 'ItemController');
    Route::get('/item-delete/{id}', 'ItemController@destroy')->name('itemDelete');


    Route::get('/foodcategory', 'FoodCategoryController@admin')->name('foodcategory');

    Route::get('/floordata', 'FloorController@data')->name('floordata');
});
/********* Admin Routes Ends ***********/

/********* Cashier Routes Start ***********/
Route::group(['prefix' => 'cashier', 'middleware' => ['auth', 'cashier']], function () {
    Route::get('/', 'HomeController@cashier')->name('cashier');
});
/********* Cashier Routes Ends ***********/

/********* Waiter Routes Start ***********/
Route::group(['prefix' => 'waiter', 'middleware' => ['auth', 'waiter']], function () {
    Route::get('/', 'HomeController@waiter')->name('waiter');
    Route::get('/table/{id}', 'TableController@table_show')->name('table_show');


});
/********* Waiter Routes Ends ***********/

/********* Kitchen Routes Start ***********/
Route::group(['prefix' => 'kitchen', 'middleware' => ['auth', 'kitchen']], function () {
    Route::get('/', 'KitchenController@index')->name('kitchen');
//        Route::get('/','KitchenController@show')->name('kitchen');
        Route::get('/statuschange/{id}','KitchenController@statuschange')->name('kitchen_status_change');
    Route::get('/clear/{id}', 'KitchenController@clear')->name('kitchenclear');
    Route::get('/notificationfromkitchen', 'KitchenController@notifier')->name('notifier');

});
/********* Kitchen Routes Ends ***********/

/********* Customer Routes Start ***********/
Route::group(['prefix' => 'customer', 'middleware' => ['auth', 'customer']], function () {
    Route::get('/', 'HomeController@customer')->name('customer');

});
/********* Customer Routes Ends ***********/

/******** Custom Routes Ends ****************/


/******************** Waiter And Admin Route *******************/
Route::post('/table/order', 'OrderController@createOrder')->name('add-order');
Route::get('/delete/order/{id}', 'OrderController@deleteOrder')->name('delete-order');
/******************** Waiter And Admin Route *******************/

app/Models/FoodCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FoodCategory extends Model
{
    protected $fillable = ['title','slug','status','categories_id','added_by','image'];

    public function dishes(){
        return $this->hasMany('App\Models\Dish','food_categories_id','id')->orderBy('title','ASC');
    }

    public function getRules($options='add'){
        return [
            'title'=>'required|string',
            'status'=>'required|in:active,inactive',
            'image'=>'sometimes|image'
        ];
    }

}

app/Http/Controllers/FoodCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\FoodCategory;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Yajra\DataTables\Facades\DataTables;

class FoodCategoryController extends Controller
{
    protected $foodCategory =null;
    protected $category =null;

    public function __construct(FoodCategory $foodCategory, Category $category){
        $this->foodCategory= $foodCategory;
        $this->category= $category;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data= $this->foodCategory->orderBy('id','DESC')->get();
        return view('food_category.index')->with('data',$data);
    }

    public function admin()
    {
        $foodcategories = FoodCategory::all();
//        dd($category);
        return view('admin.foodcategory')->with('foodcategories',$foodcategories);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->category=$this->category->get();
        $return_category =array();
        foreach($this->category as $key=>$category){
            $return_category[$category->id]= $category->title;

        }

        return view('food_category.form')->with('category',$return_category);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules= $this->foodCategory->getRules();
        $request->validate($rules);
        $data=$request->all();

        $slug=\Str::slug($request->title);
        $found =$this->foodCategory->where('slug',$slug)->count();

        if($found > 0){
            $slug .=date('YmdHis');
        }
        $data['slug']= $slug;

        if($request->image){
            $path= public_path().('/images/foods');
            if(!File::exists($path)){
                File::makeDirectory($path,0777,true,true);
            }
            $filename = "Foods-".date('YmdHis').rand(0,100).".".$request->image->getClientOriginalExtension();
            $request->image->move($path,$filename);
            $data['image'] =$filename;
        }
        $data['added_by'] =Auth::user()->id;
        $this->foodCategory =$this->foodCategory->fill($data);
        $success= $this->foodCategory->save();
        return redirect()->route('foodCategory.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->category=$this->category->get();
        $return_category =array();
        foreach($this->category as $key=>$category){
            $return_category[$category->id]= $category->title;

        }

        $this->foodCategory=$this->foodCategory->find($id);
        if(!$this->foodCategory){
            return redirect()->route('foodCategory.index');
        }
        return view('food_category.form')->with('edit_data',$this->foodCategory)->with('category',$return_category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules= $this->foodCategory->getRules();
        $request->validate($rules);

        $data=$request->all();
        $this->foodCategory=$this->foodCategory->find($id);
        if(!$this->foodCategory){
            return redirect()->route('foodCategory.index');
        }

        if($request->image){
            $path= public_path().('/images/foods');

            $filename = "Foods-".date('YmdHis').rand(0,100).".".$request->image->getClientOriginalExtension();
            $success= $request->image->move($path,$filename);
            if($success){
                $data['image'] =$filename;
                $old_image =$this->foodCategory->image;
                if($old_image !=null && file_exists(public_path().'/images/foods/'.$this->foodCategory->image)){
                    unlink(public_path().'/images/foods/'.$this->foodCategory->image);
                }
            }

        }

        $this->foodCategory=$this->foodCategory->fill($data);
        $this->foodCategory->save();
        return redirect()->route('foodCategory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->foodCategory=$this->foodCategory->find($id);
        if(!$this->foodCategory){
            return redirect()->route('foodCategory.index');
        }

        $old_image =$this->foodCategory->image;
        $this->foodCategory->delete();
        if($old_image !=null && file_exists(public_path().'/images/foods/'.$this->foodCategory->image)){
            unlink(public_path().'/images/foods/'.$this->foodCategory->image);
        }
        return redirect()->route('foodCategory.index');
    }
    public function data()
    {
        $foodcategory = FoodCategory::all();
        return Datatables::of($foodcategory)->addColumn('action', function ($foodcategory) {
            return
                '<span>
                              <a href="' . route('foodCategory.edit', $foodcategory->id) . '">
                                   <button class="btn btn-warning">Edit</button>
                              </a>
                        </span>'.
                '&nbsp;' .
                '<span>
                               <a href="' .route('foodCategoryDelete', $foodcategory->id) .
                'onclick="return confirm("Are you sure you want to delete?")">' .
                '<button class="btn btn-danger">Delete</button>
                                                    </a>
                                                </span>';
        })->rawColumns(['action' => 'action'])
            ->make(true);

    }
}

resources/views/food_category/form.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>Please {{ isset($edit_data) ? 'update' : 'add'}} the form: </h2>
   
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                @if(isset($edit_data))
                <form action="{{ route('foodCategory.update',$edit_data->id) }}" method="post" enctype="multipart/form-data">
                    @method('PUT')
                @else
              <form action="{{ route('foodCategory.store') }}" method="post" enctype="multipart/form-data">
              @endif
              @csrf
              <div class="form-group row">
                <label class="col-sm-3">Title:  </label>
                  <div class="col-sm-9">
                    <input type="text" name="title" class="form-control form-control-sm" value="{{ isset($edit_data) ? @$edit_data->title : old('title')}}">
                    @if($errors->has('title'))  
                    <span class="alert-danger"> {{$errors->first('title')}} </span>   
                    @endif              
                  </div>
                </div>

               
                <div class="form-group row">
                <label class="col-sm-3">Status:   </label>
                  <div class="col-sm-9">
                 <select name="status" id="status" class="form-control">
                 <option value="active"{{ (isset($edit_data) && ($edit_data->status=='active') ? 'selected' : '') }}>Active</option>
                    <option value="inactive"{{ (isset($edit_data) && ($edit_data->status=='inactive') ? 'selected' : '') }}>Inactive</option>
                 </select>
                    @if($errors->has('status'))  
                    <span class="alert-danger"> {{$errors->first('status')}} </span>   
                    @endif                   
                  </div>
                </div>
               
                <div class="form-group row">
                                   {{ Form::label('categories_id','Category: ',['class'=>'col-sm-3']) }}
                                    <div class="col-sm-9">
                                        {{Form::select('categories_id',isset($category) ? $category : [],@$edit_data->categories_id,['class'=>'form-control','id'=>'categories_id','placeholder'=>'--Select any one--']) }}
                                        @if($errors->has('categories_id'))
                                            <span class="alert-danger">
                                                {{ $errors->first('categories_id') }}
                                            </span>
                                        @endif
                                    </div>
                                </div>

                <div class="form-group row">
                <label class="col-sm-3">Image:</label>
                  <div class="col-sm-4">
                    <input type="file" name="image" class="form-control form-control-sm"  accept="image/*">
                    @if($errors->has('image'))  
                    <span class="alert-danger"> {{$errors->first('image')}} </span>   
                    @endif 
                    </div>      
                    @if(isset($edit_data) && file_exists(public_path().'/images/foods/'.$edit_data->image))
                    <div class="col-sm-4">
                      <img style="max-width:150px;" src="{{ asset('images/foods/'.$edit_data->image) }}" alt="no image found" class="img img-responsive img-thumbnail">
                    </div>
                    @endif
                                 
                 
                </div>


                <button class="btn-success" type="submit">Send</button>

                <button class="btn-danger" type="reset">Reset</button>

              </form>

            </div>
        </div>
    </div>

    
</body>
</html>

resources/views/food_category/index.blade.php
@extends('layouts.app')
@section('styles')
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link  href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
@endsection
@section('scripts')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        $(function() {
            $('#food_category').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ url('foodcategorydata') }}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'title', name: 'title' },
                    { data: 'categories_id', name: 'categories_id' },
                    { data: 'action', name: 'action' }
                ]
            });
        });
    </script>
@endsection
@section('content')
<body>
    <a href="{{ route('foodCategory.create')}}"><button class="btn btn-success float-right" >Add Data</button></a>
   <div class="container">
       <div class="row">
           <div class="col sm-14">
           <table border="1px" class="table table-striped" id="food_category">
        <thead class="thead-dark">
            <th>Id</th>
            <th>Title</th>
            <th>category</th>
            <th>Action</th>
        </thead>
        <tbody>
                        @foreach($data as $key=>$value)
                         <tr>
                             <td>{{$key+1}}</td>
                             <td>{{$value->title}}</td>
                             <td>{{$value->categories_id}}</td>
                             <td>
                                 <a class="btn btn-success" href="{{ route('user.edit',$value->id) }}">Edit</a>
                                 <a class="btn btn-success" href="{{ route('foodCategoryDelete',$value->id) }}" onclick="return confirm('Are you sure to delete')">Delete</a>
                                </td>
                         </tr>
                         @endforeach   
                    </tbody>



    </table>
           </div>
       </div>
   </div>

</body>
@endsection