routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function () {
    Route::put('table', 'TableController@changeStatus')->name('change-status');
    Route::post('order/{dish_id}', 'OrderController@createOrder')->name('order-dish');
    Route::get('orderkitchen', 'OrderController@createkitchenOrder')->name('order-dish-kitchen');
    Route::get('/apiorder/{id}', 'TableController@orderdataapi');
    Route::get('checkout/{order_code}/{table_id}', 'OrderController@makePayment')->name('make-payment');
    Route::get('/orderconfirmed/{tableId}', 'OrderController@OrderConfirmed')->name('order-confirmed');
    Route::get('/floordata', 'FloorController@data')->name('floordata');
    Route::get('/userdata', 'UserController@data')->name('userdata');
    Route::get('/categorydata', 'CategoryController@data')->name('categorydata');
    Route::get('/foodcategorydata', 'FoodCategoryController@data')->name('foodcategorydata');
    Route::get('/tabledata', 'TableController@data')->name('tabledata');
    Route::get('/itemdata', 'ItemController@data')->name('itemdata');

});
/******** Custom Routes Start ****************/
/********* Admin Routes Start ***********/
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'HomeController@admin')->name('admin');

    Route::get('/add-data', 'HomeController@addData')->name('addData');

    Route::resource('table', 'TableController');
    Route::get('/table', 'TableController@tableIndex')->name('tableIndex');
    Route::get('table-delete/{id}', 'TableController@destroy')->name('tableDelete');


    Route::resource('user', 'UserController');
    Route::get('/user-delete/{id}', 'UserController@destroy')->name('deleteUser');

    Route::resource('floor', 'FloorController');
    Route::get('floor-delete/{id}', 'FloorController@destroy')->name('floorDelete');

    Route::get('/release/{table_id}', 'TableController@releaseTable')->name('release-table');

    Route::get('/category', 'CategoryController@admin')->name('category');

    Route::resource('category', 'CategoryController');
    Route::get('category-delete/{id}', 'CategoryController@destroy')->name('categoryDelete');

    Route::resource('foodCategory', 'FoodCategoryController');
    Route::get('food-Category-Delete/{id}', 'FoodCategoryController@destroy')->name('foodCategoryDelete');

    Route::get('/item', 'ItemController@admin')->name('item');


    Route::resource('item', 'ItemController');
    Route::get('/item-delete/{id}', 'ItemController@destroy')->name('itemDelete');


    Route::get('/foodcategory', 'FoodCategoryController@admin')->name('foodcategory');

    Route::get('/floordata', 'FloorController@data')->name('floordata');
});
/********* Admin Routes Ends ***********/

/********* Cashier Routes Start ***********/
Route::group(['prefix' => 'cashier', 'middleware' => ['auth', 'cashier']], function () {
    Route::get('/', 'HomeController@cashier')->name('cashier');
});
/********* Cashier Routes Ends ***********/

/********* Waiter Routes Start ***********/
Route::group(['prefix' => 'waiter', 'middleware' => ['auth', 'waiter']], function () {
    Route::get('/', 'HomeController@waiter')->name('waiter');
    Route::get('/table/{id}', 'TableController@table_show')->name('table_show');


});
/********* Waiter Routes Ends ***********/

/********* Kitchen Routes Start ***********/
Route::group(['prefix' => 'kitchen', 'middleware' => ['auth', 'kitchen']], function () {
    Route::get('/', 'KitchenController@index')->name('kitchen');
//        Route::get('/','KitchenController@show')->name('kitchen');
        Route::get('/statuschange/{id}','KitchenController@statuschange')->name('kitchen_status_change');
    Route::get('/clear/{id}', 'KitchenController@clear')->name('kitchenclear');
    Route::get('/notificationfromkitchen', 'KitchenController@notifier')->name('notifier');

});
/********* Kitchen Routes Ends ***********/

/********* Customer Routes Start ***********/
Route::group(['prefix' => 'customer', 'middleware' => ['auth', 'customer']], function () {
    Route::get('/', 'HomeController@customer')->name('customer');

});
/********* Customer Routes Ends ***********/

/******** Custom Routes Ends ****************/


/******************** Waiter And Admin Route *******************/
Route::post('/table/order', 'OrderController@createOrder')->name('add-order');
Route::get('/delete/order/{id}', 'OrderController@deleteOrder')->name('delete-order');
/******************** Waiter And Admin Route *******************/

app/Models/Floor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Floor extends Model
{
    protected $fillable = ['name','slug','status','image'];

    public function tables(){
        return $this->hasMany('App\Models\Table','floor_id','id');
    }

    public function counts(){
        return $this->hasMany('App\Models\Table','floor_id','id')->where('occupied','!=','occupied');
    }

    public function getAllFloors(){
        return $this->with(['tables','counts'])->get();
    }

    public function getRules($options='add'){
        return [
            'name'=>'required|string',
            'status'=>'required|in:active,inactive',
            'image'=>'sometimes|image'
        ];
    }
}

app/Http/Controllers/FloorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Floor;
use App\Student;
use Illuminate\Http\Request;
use Illuminate\support\Facades\File;
use Yajra\DataTables\Facades\DataTables;

class FloorController extends Controller
{
    protected $floor =null;
    public function __construct(Floor $floor){
        $this->floor= $floor;
    }
    public function index()
    {
        $data= $this->floor->get();
        return view('floor.index')->with('data',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('floor.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $rules= $this->floor->getRules();
        $request->validate($rules);
        $data=$request->all();
        $slug=\Str::slug($request->name);
        $found =$this->floor->where('slug',$slug)->count();

        if($found > 0){
            $slug .=date('YmdHis');
        }
        $data['slug']= $slug;
        if($request->image){
        $path= public_path().('/images/floors');
        if(!File::exists($path)){
            File::makeDirectory($path,0777,true,true);
        }
        $filename = "Floors-".date('YmdHis').rand(0,100).".".$request->image->getClientOriginalExtension();
        $request->image->move($path,$filename);
        $data['image'] =$filename;
        }

        $this->floor =$this->floor->fill($data);
        $success= $this->floor->save();
        return redirect()->route('floor.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $this->floor=$this->floor->find($id);
        if(!$this->floor){
            return redirect()->route('floor.index');
        }
        return view('floor.form')->with('edit_data',$this->floor);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->floor=$this->floor->find($id);
        if(!$this->floor){
            return redirect()->route('floor.index');
        }
        $old_image =$this->floor->image;
        $rules= $this->floor->getRules('update');
        $request->validate($rules);
        $data=$request->all();
        if($request->image){
            $path= public_path().('/images/floors');

            $filename = "Floors-".date('YmdHis').rand(0,100).".".$request->image->getClientOriginalExtension();
            $success= $request->image->move($path,$filename);
            if($success){
                $data['image'] =$filename;
                if($old_image !=null &&  file_exists(public_path().'/images/floors/'.$this->floor->image)){
                    unlink(public_path().'/images/floors/'.$this->floor->image);
                }
            }

        }
        $this->floor=$this->floor->fill($data);
        $this->floor->save();
        return redirect()->route('floor.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->floor=$this->floor->find($id);
        if(!$this->floor){
            return redirect()->route('floor.index');
        }
        $old_image =$this->floor->image;
        if($old_image !=null &&  file_exists(public_path().'/images/floors/'.$this->floor->image)){
            unlink(public_path().'/images/floors/'.$this->floor->image);
        }

        $this->floor->delete();
        return redirect()->route('floor.index');
    }
    public function data()
    {
        $floor = Floor::all();
        return Datatables::of($floor)->addColumn('action', function ($floor) {
            return
                '<span>
                              <a href="' . route('floor.edit', $floor->id) . '">
                                   <button class="btn btn-warning">Edit</button>
                              </a>
                        </span>'.
                '&nbsp;' .
                '<span>
                               <a href="' .route('floorDelete', $floor->id) .
                'onclick="return confirm("Are you sure you want to delete?")">' .
                '<button class="btn btn-danger">Delete</button>
                                                    </a>
                                                </span>';
        })->rawColumns(['action' => 'action'])
            ->make(true);

    }
}

resources/views/floor/form.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>Please {{ isset($edit_data) ? 'update' : 'add'}} the form: </h2>
   
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                @if(isset($edit_data))
                <form action="{{ route('floor.update',$edit_data->id) }}" method="post" enctype="multipart/form-data">
                    @method('PUT')
                @else
              <form action="{{ route('floor.store') }}" method="post" enctype="multipart/form-data">
              @endif
              @csrf
              <div class="form-group row">
                <label class="col-sm-3">Name:  </label>
                  <div class="col-sm-9">
                    <input type="text" name="name" class="form-control form-control-sm" value="{{ isset($edit_data) ? @$edit_data->name : old('name')}}">
                    @if($errors->has('name'))  
                    <span class="alert-danger"> {{$errors->first('name')}} </span>   
                    @endif              
                  </div>
                </div>

                <div class="form-group row">
                <label class="col-sm-3">Status:   </label>
                  <div class="col-sm-9">
                 <select name="status" id="status" class="form-control">
                 <option value="active"{{ (isset($edit_data) && ($edit_data->status=='active') ? 'selected' : '') }}>Active</option>
                    <option value="inactive"{{ (isset($edit_data) && ($edit_data->status=='inactive') ? 'selected' : '') }}>Inactive</option>
                
                 </select>
                    @if($errors->has('status'))  
                    <span class="alert-danger"> {{$errors->first('status')}} </span>   
                    @endif                   
                  </div>
                </div>

                <div class="form-group row">
                <label class="col-sm-3">Image:</label>
                  <div class="col-sm-4">
                    <input type="file" name="image" class="form-control form-control-sm"  accept="image/*">
                   
                    @if($errors->has('image'))  
                    <span class="alert-danger"> {{$errors->first('image')}} </span>   
                    @endif 
                    </div>      
                   
                    @if(isset($edit_data) && file_exists(public_path().'/images/floors/'.$edit_data->image))
                    <div class="col-sm-4">
                      <img style="max-width:150px;" src="{{ asset('images/floors/'.$edit_data->image) }}" alt="no image found" class="img img-responsive img-thumbnail">
                    </div>
                    @endif
                                 
                 
                </div>

             

                <button class="btn-success" type="submit">Send</button>

                <button class="btn-danger" type="reset">Reset</button>

              </form>

            </div>
        </div>
    </div>

    
</body>
</html>

resources/views/floor/index.blade.php
@extends('layouts.app')
@section('styles')
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link  href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
@endsection
@section('scripts')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script>
    $(function() {
        $('#floor').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ url('floordata') }}',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'name', name: 'name' },
                { data: 'status', name: 'status' },
                { data: 'action', name: 'action' }
            ]
        });
    });
</script>
    @endsection
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

@section('content')
    <a href="{{ route('floor.create')}}"><button class="btn btn-success float-right" >Add Data</button></a>
   <div class="container">
       <div class="row">
           <div class="col sm-12">
           <table border="1px" class="table table-striped" id="floor">
        <thead class="thead-dark">
            <th>Id</th>
            <th>Name</th>
            <th>Status</th>
            <th>Action</th>
        </thead>
        <tbody>
                        @foreach($data as $key=>$value)
                         <tr>
                             <td>{{$key+1}}</td>
                             <td>{{$value->name}}</td>
                             <td>{{$value->status}}</td>
                           
                             <td>
                                 <a class="btn btn-success" href="{{ route('user.edit',$value->id) }}">Edit</a>
                                 <a class="btn btn-success" href="{{ route('itemDelete',$value->id) }}" onclick="return confirm('Are you sure to delete')">Delete</a>
                                </td>
                         </tr>
                         @endforeach   
                    </tbody>




    </table>
           </div>
       </div>
   </div>

@endsection