routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function () {
    Route::put('table', 'TableController@changeStatus')->name('change-status');
    Route::post('order/{dish_id}', 'OrderController@createOrder')->name('order-dish');
    Route::get('orderkitchen', 'OrderController@createkitchenOrder')->name('order-dish-kitchen');
    Route::get('/apiorder/{id}', 'TableController@orderdataapi');
    Route::get('checkout/{order_code}/{table_id}', 'OrderController@makePayment')->name('make-payment');
    Route::get('/orderconfirmed/{tableId}', 'OrderController@OrderConfirmed')->name('order-confirmed');
    Route::get('/floordata', 'FloorController@data')->name('floordata');
    Route::get('/userdata', 'UserController@data')->name('userdata');
    Route::get('/categorydata', 'CategoryController@data')->name('categorydata');
    Route::get('/foodcategorydata', 'FoodCategoryController@data')->name('foodcategorydata');
    Route::get('/tabledata', 'TableController@data')->name('tabledata');
    Route::get('/itemdata', 'ItemController@data')->name('itemdata');

});
/******** Custom Routes Start ****************/
/********* Admin Routes Start ***********/
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'HomeController@admin')->name('admin');

    Route::get('/add-data', 'HomeController@addData')->name('addData');

    Route::resource('table', 'TableController');
    Route::get('/table', 'TableController@tableIndex')->name('tableIndex');
    Route::get('table-delete/{id}', 'TableController@destroy')->name('tableDelete');


    Route::resource('user', 'UserController');
    Route::get('/user-delete/{id}', 'UserController@destroy')->name('deleteUser');

    Route::resource('floor', 'FloorController');
    Route::get('floor-delete/{id}', 'FloorController@destroy')->name('floorDelete');

    Route::get('/release/{table_id}', 'TableController@releaseTable')->name('release-table');

    Route::get('/category', 'CategoryController@admin')->name('category');

    Route::resource('category', 'CategoryController');
    Route::get('category-delete/{id}', 'CategoryController@destroy')->name('categoryDelete');

    Route::resource('foodCategory', 'FoodCategoryController');
    Route::get('food-Category-Delete/{id}', 'FoodCategoryController@destroy')->name('foodCategoryDelete');

    Route::get('/item', 'ItemController@admin')->name('item');


    Route::resource('item', 'ItemController');
    Route::get('/item-delete/{id}', 'ItemController@destroy')->name('itemDelete');


    Route::get('/foodcategory', 'FoodCategoryController@admin')->name('foodcategory');

    Route::get('/floordata', 'FloorController@data')->name('floordata');
});
/********* Admin Routes Ends ***********/

/********* Cashier Routes Start ***********/
Route::group(['prefix' => 'cashier', 'middleware' => ['auth', 'cashier']], function () {
    Route::get('/', 'HomeController@cashier')->name('cashier');
});
/********* Cashier Routes Ends ***********/

/********* Waiter Routes Start ***********/
Route::group(['prefix' => 'waiter', 'middleware' => ['auth', 'waiter']], function () {
    Route::get('/', 'HomeController@waiter')->name('waiter');
    Route::get('/table/{id}', 'TableController@table_show')->name('table_show');


});
/********* Waiter Routes Ends ***********/

/********* Kitchen Routes Start ***********/
Route::group(['prefix' => 'kitchen', 'middleware' => ['auth', 'kitchen']], function () {
    Route::get('/', 'KitchenController@index')->name('kitchen');
//        Route::get('/','KitchenController@show')->name('kitchen');
        Route::get('/statuschange/{id}','KitchenController@statuschange')->name('kitchen_status_change');
    Route::get('/clear/{id}', 'KitchenController@clear')->name('kitchenclear');
    Route::get('/notificationfromkitchen', 'KitchenController@notifier')->name('notifier');

});
/********* Kitchen Routes Ends ***********/

/********* Customer Routes Start ***********/
Route::group(['prefix' => 'customer', 'middleware' => ['auth', 'customer']], function () {
    Route::get('/', 'HomeController@customer')->name('customer');

});
/********* Customer Routes Ends ***********/

/******** Custom Routes Ends ****************/


/******************** Waiter And Admin Route *******************/
Route::post('/table/order', 'OrderController@createOrder')->name('add-order');
Route::get('/delete/order/{id}', 'OrderController@deleteOrder')->name('delete-order');
/******************** Waiter And Admin Route *******************/

app/Http/Controllers/TableController.php
<?php

namespace App\Http\Controllers;

use App\Models\Floor;
use App\Models\FoodCategory;
use App\Models\Category;
use App\Models\Order;
use App\Models\Table;
use App\User;
use Facade\Ignition\Tabs\Tab;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;


class TableController extends Controller
{
    protected $table_obj = null;
    protected $food_category = null;
    protected $category = null;
    protected $order = null;

    public function __construct(Table $table_obj, FoodCategory $food_category, Category $category, Order $order, Floor $floor, User $user)
    {
        $this->table_obj = $table_obj;
        $this->category = $category;
        $this->food_category = $food_category;
        $this->order = $order;
        $this->floor = $floor;
        $this->user = $user;

        $this->middleware(['auth']);
    }

    public function releaseTable(Request $request)
    {
        dd($request);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->table_obj = $this->table_obj->get();

        return view('admin.table')
            ->with('all_tables', $this->table_obj);
    }

    public function tableIndex()
    {
        $this->table_obj = $this->table_obj->orderBy('id', 'DESC')->get();

        return view('table.index')
            ->with('data', $this->table_obj);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->floor = $this->floor->get();
        $return_floor = array();
        foreach ($this->floor as $key => $floor) {
            $return_floor[$floor->id] = $floor->name;
        }
        $this->user = $this->user->where('role', 'waiter')->get();
        $return_waiter = array();
        foreach ($this->user as $key => $user) {
            $return_waiter[$user->id] = $user->name;
        }
        return view('table.form')->with('waiter', $return_waiter)->with('floor', $return_floor);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $rules = $this->table_obj->getRules();
        $request->validate($rules);
        $data = $request->all();

        if ($request->icon) {
            $path = public_path() . ('/images/tables');
            if (!File::exists($path)) {
                File::makeDirectory($path, 0777, true, true);
            }
            $filename = "Tables-" . date('YmdHis') . rand(0, 100) . "." . $request->icon->getClientOriginalExtension();
            $request->icon->move($path, $filename);
            $data['icon'] = $filename;
        }

        $data['added_by'] = Auth::user()->id;


        $this->table_obj = $this->table_obj->fill($data);
        $success = $this->table_obj->save();
        return redirect()->route('tableIndex');
    }


    public function show($id)
    {
        $this->table_obj = $this->table_obj->find($id);
        if (!$this->table_obj) {
            return redirect()->back();
        }
        $this->category = $this->category->getAllCategories();
        $this->order = $this->order->getOrderByTable($id);

        return view('admin.table')
            ->with('categories', $this->category)
            ->with('orders', $this->order)
            ->with('table_data', $this->table_obj);
    }

    public function edit($id)
    {
        $this->floor = $this->floor->get();
        $return_floor = array();
        foreach ($this->floor as $key => $floor) {
            $return_floor[$floor->id] = $floor->name;
        }
        $this->user = $this->user->where('role', 'waiter')->get();
        $return_waiter = array();
        foreach ($this->user as $key => $user) {
            $return_waiter[$user->id] = $user->name;
        }

        $this->table_obj = $this->table_obj->find($id);
        if (!$this->table_obj) {
            return redirect()->route('tableIndex');
        }
        return view('table.form')->with('edit_data', $this->table_obj)->with('waiter', $return_waiter)->with('floor', $return_floor);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = $this->table_obj->getRules();
        $request->validate($rules);

        $data = $request->all();
        $this->table_obj = $this->table_obj->find($id);
        if (!$this->table_obj) {
            return redirect()->route('tableIndex');
        }


        if ($request->icon) {
            $old_image = $this->table_obj->icon;
            $path = public_path() . ('/images/tables');
            $filename = "tables-" . date('YmdHis') . rand(0, 100) . "." . $request->icon->getClientOriginalExtension();
            $success = $request->icon->move($path, $filename);
            if ($success) {
                $data['icon'] = $filename;
                if ($old_image != null && file_exists(public_path() . '/images/tables/' . $this->table_obj->icon)) {
                    unlink(public_path() . '/images/tables/' . $this->table_obj->icon);
                }
            }

        }

        $this->table_obj = $this->table_obj->fill($data);
        $this->table_obj->save();
        return redirect()->route('tableIndex');
    }


    public function destroy($id)
    {
        $this->table_obj = $this->table_obj->find($id);
        if (!$this->table_obj) {
            return redirect()->route('tableIndex');
        }
        $old_image = $this->table_obj->icon;
        if ($old_image != null && file_exists(public_path() . '/images/tables/' . $this->table_obj->icon)) {
            unlink(public_path() . '/images/tables/' . $this->table_obj->icon);
        }
        $this->table_obj->delete();
        return redirect()->route('tableIndex');
    }

    public function changeStatus(Request $request)
    {
        $this->table_obj = $this->table_obj->find($request->table_id);
        if (!$this->table_obj) {
            return response()->json(['status' => false, 'msg' => 'Table does not exists.', 'data' => null]);
        }
        $data = array(
            'occupied' => $request->status,
            'waiter_id' => $request->user()->id
        );
        // dd($data);

        $this->table_obj->fill($data);
        $status = $this->table_obj->save();
        if ($status) {
            return response()->json(['status' => true, 'msg' => 'Status changed successfully.', 'data' => null]);
        } else {
            return response()->json(['status' => false, 'msg' => 'Error changing status of table.', 'data' => null]);
        }
    }

    public function orderdataapi($id)
    {
        $orders = $this->order->getOrderByTable($id);
        $table_id = $id;
        // return response()->view("waiter._orderTable", compact('orders'));
        return response()->json(['status'=>true, 'html' => view('waiter._orderTable', compact('orders', 'table_id'))->render(), 'msg' => 'Order Table Reseted']);
    }

    public function tablereset($id)
    {
        $table = Table::where('id', $id)->update(['occupied' => 'open']);

    }

    public function table_show($id)
    {
        $this->table_obj = $this->table_obj->find($id);
        if (!$this->table_obj) {
            return redirect()->back();
        }
        $this->category = $this->category->getAllCategories();
        $this->order = $this->order->getOrderByTable($id);
        
        return view('waiter.table')
            ->with('categories', $this->category)
            ->with('orders', $this->order)
            ->with('table_data', $this->table_obj);
    }

    public function data()
    {
        $table = Table::all();
        return Datatables::of($table)->addColumn('action', function ($table) {
            return
                '<span>
                              <a href="' . route('table.edit', $table->id) . '">
                                   <button class="btn btn-warning">Edit</button>
                              </a>
                        </span>' .
                '&nbsp;' .
                '<span>
                               <a href="' . route('tableDelete', $table->id) .
                'onclick="return confirm("Are you sure you want to delete?")">' .
                '<button class="btn btn-danger">Delete</button>
                                                    </a>
                                                </span>';
        })->rawColumns(['action' => 'action'])
            ->make(true);
    }
}

resources/views/table/form.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>Please {{ isset($edit_data) ? 'update' : 'add'}} the form: </h2>
   
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                @if(isset($edit_data))
                <form action="{{ route('table.update',$edit_data->id) }}" method="post" enctype="multipart/form-data">
                    @method('PUT')
                @else
              <form action="{{ route('table.store') }}" method="post" enctype="multipart/form-data">
              @endif
              @csrf
              <div class="form-group row">
                <label class="col-sm-3">Table number:  </label>
                  <div class="col-sm-9">
                    <input type="text" name="table_no" class="form-control form-control-sm" value="{{ isset($edit_data) ? @$edit_data->table_no : old('table_no')}}">
                    @if($errors->has('table_no'))  
                    <span class="alert-danger"> {{$errors->first('table_no')}} </span>   
                    @endif              
                  </div>
                </div>

                <div class="form-group row">
                <label class="col-sm-3">Capacity  </label>
                  <div class="col-sm-9">
                    <input type="number" name="capacity" class="form-control form-control-sm" value="{{ isset($edit_data) ? @$edit_data->capacity : old('capacity')}}">
                    @if($errors->has('capacity'))  
                    <span class="alert-danger"> {{$errors->first('capacity')}} </span>   
                    @endif              
                  </div>
                </div>

               
                <div class="form-group row">
                <label class="col-sm-3">Status:   </label>
                  <div class="col-sm-9">
                 <select name="status" id="status" class="form-control">
                 <option value="active"{{ (isset($edit_data) && ($edit_data->status=='active') ? 'selected' : '') }}>Active</option>
                    <option value="inactive"{{ (isset($edit_data) && ($edit_data->status=='inactive') ? 'selected' : '') }}>Inactive</option>
                 </select>
                    @if($errors->has('status'))  
                    <span class="alert-danger"> {{$errors->first('status')}} </span>   
                    @endif                   
                  </div>
                </div>

                <div class="form-group row">
                <label class="col-sm-3">Occupied:   </label>
                  <div class="col-sm-9">
                 <select name="occupied" id="occupied" class="form-control">
                 <option value="occupied"{{ (isset($edit_data) && ($edit_data->status=='occupied') ? 'selected' : '') }}>occupied</option>
                    <option value="reserved"{{ (isset($edit_data) && ($edit_data->status=='reserved') ? 'selected' : '') }}>reserved</option>
                    <option value="open"{{ (isset($edit_data) && ($edit_data->status=='open') ? 'selected' : '') }}>open</option>
                 </select>
                    @if($errors->has('occupied'))  
                    <span class="alert-danger"> {{$errors->first('occupied')}} </span>   
                    @endif                   
                  </div>
                </div>
               


               
                <div class="form-group row">
                                   {{ Form::label('waiter_id','Waiter_id: ',['class'=>'col-sm-3']) }}
                                    <div class="col-sm-9">
                                        {{Form::select('waiter_id',isset($waiter) ? $waiter : [],@$edit_data->waiter_id,['class'=>'form-control','id'=>'waiter_id','placeholder'=>'--Select any one--']) }}
                                        @if($errors->has('waiter_id'))
                                            <span class="alert-danger">
                                                {{ $errors->first('waiter_id') }}
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                   {{ Form::label('floor_id','floor_id: ',['class'=>'col-sm-3']) }}
                                    <div class="col-sm-9">
                                        {{Form::select('floor_id',isset($floor) ? $floor : [],@$edit_data->floor_id,['class'=>'form-control','id'=>'floor_id','placeholder'=>'--Select any one--']) }}
                                        @if($errors->has('floor_id'))
                                            <span class="alert-danger">
                                                {{ $errors->first('floor_id') }}
                                            </span>
                                        @endif
                                    </div>
                                </div>

                <div class="form-group row">
                <label class="col-sm-3">Icon:</label>
                  <div class="col-sm-4">
                    <input type="file" name="icon" class="form-control form-control-sm"  accept="image/*">
                    @if($errors->has('icon'))  
                    <span class="alert-danger"> {{$errors->first('icon')}} </span>   
                    @endif 
                    </div>      
                    @if(isset($edit_data) && file_exists(public_path().'/images/tables/'.$edit_data->icon))
                    <div class="col-sm-4">
                      <img style="max-width:150px;" src="{{ asset('images/tables/'.$edit_data->icon) }}" alt="no image found" class="img img-responsive img-thumbnail">
                    </div>
                    @endif
                                 
                 
                </div>


                <button class="btn-success" type="submit">Send</button>

                <button class="btn-danger" type="reset">Reset</button>

              </form>

            </div>
        </div>
    </div>

    
</body>
</html>

resources/views/table/index.blade.php
@extends('layouts.app')
@section('styles')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link  href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
@endsection
@section('scripts')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        $(function() {
            $('#table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ url('tabledata') }}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'floor_id', name: 'floor_id' },
                    { data: 'capacity', name: 'capacity' },
                    { data: 'status', name: 'status' },
                    { data: 'action', name: 'action' }
                ]
            });
        });
    </script>
@endsection
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
@section('content')
    <a href="{{ route('table.create')}}"><button class="btn btn-success float-right" >Add Data</button></a>
   <div class="container">
       <div class="row">
           <div class="col sm-14">
           <table border="1px" class="table table-striped" id="table">
        <thead class="thead-dark">

            <th>Id</th>
            <th>floor_id</th>
            <th>Capacity</th>
            <th>status</th>
            <th>Action</th>
        </thead>
        <tbody>
                        @foreach($data as $key=>$value)
                         <tr>
                             <td>{{$key+1}}</td>
                             <td>{{$value->floor_id}}</td>
                             <td>{{$value->capacity}}</td>
                             <td>{{$value->status}}</td>
                             <td>
                                 <a class="btn btn-success" href="{{ route('user.edit',$value->id) }}">Edit</a>
                                 <a class="btn btn-success" href="{{ route('tableDelete',$value->id) }}" onclick="return confirm('Are you sure to delete')">Delete</a>
                                </td>
                         </tr>
                         @endforeach   
                    </tbody>




    </table>
           </div>
       </div>
   </div>
@endsection